## Обязательная часть

Будем осуществлять работу с непростым [набором данных](https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv) о состоянии здоровья лошадей, испытывающих кишечные колики. 

### Задание 1. Базовое изучение

Изучить представленный набор данных на основе [описания его столбцов](https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.names) и выбрать 8 столбцов для дальнейшего изучения (среди них должны быть как числовые, так и категориальные). Провести расчет базовых метрик для них, кратко описать результаты.

### Задание 2. Работа с выбросами

В выбранных числовых столбцах найти выбросы, выдвинуть гипотезы об их причинах и проинтерпретировать результаты. Принять и обосновать решение о дальнейшей работе с ними.

### Задание 3. Работа с пропусками

Рассчитать количество выбросов для всех выбранных столбцов. Принять и обосновать решение о методе работы с пропусками по каждому столбцу, сформировать датафрейм, в котором пропуски будут отсутствовать.

In [285]:
import pandas as pd
import numpy as np

In [286]:
# Просмотрев данные, сделал два важных замечания
# Нет названия столбцев, их добавлю при открытии
# Отсутсвие данных в общем виде соответсвтует знаку ?
# Все строки должны иметь числовые значения

# Поэтому переведу все данные в числа и заменю ? на nan

In [287]:
# Чтобы видеть все столбцы
pd.set_option('display.max_columns', None)

In [288]:
# Откроем файл и зададим всем столбцам названия
headers = ['surgery', 'Age', 'Hospital Number', 'rectal temperature', 'pulse', 'respiratory rate', 
                             'temperature of extremities', 'peripheral pulse', 'mucous membranes', 'capillary refill time', 
                             'pain', 'peristalsis', 'abdominal distension', 'nasogastric tube', 'nasogastric reflux', 
                             'nasogastric reflux PH', 'rectal examination - feces', 'abdomen', 'packed cell volume', 
                             'total protein', 'abdominocentesis appearance', 'abdomcentesis total protein', 'outcome', 
                             'surgical lesion', 'type of lesion 1', 'type of lesion 2', 'type of lesion 3', 'cp_data']


horses = pd.read_csv('C:\\Users\\roman\\Learning\\PYDA13\\git_rep\\PYDA-DZ\\Stat\\horse_data.csv', names=headers)

# Перевод все в числа и замена ? на nan

horses = horses.replace('?', '-9999')
horses = horses.astype(float).replace(-9999, np.nan)
horses.describe()

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,pain,peristalsis,abdominal distension,nasogastric tube,nasogastric reflux,nasogastric reflux PH,rectal examination - feces,abdomen,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion 1,type of lesion 2,type of lesion 3,cp_data
count,299.000000,300.000000,3.000000e+02,240.000000,276.000000,242.000000,244.000000,231.000000,253.000000,268.000000,245.00000,256.000000,244.000000,196.000000,194.000000,53.000000,198.000000,182.000000,271.000000,267.000000,135.000000,102.000000,299.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,1.397993,1.640000,1.085889e+06,38.167917,71.913043,30.417355,2.348361,2.017316,2.853755,1.305970,2.95102,2.917969,2.266393,1.755102,1.582474,4.707547,2.757576,3.692308,46.295203,24.456929,2.037037,3.019608,1.551839,1.363333,3657.880000,90.226667,7.363333,1.670000
std,0.490305,2.173972,1.529801e+06,0.732289,28.630557,17.642231,1.045054,1.042428,1.620294,0.477629,1.30794,0.976744,1.065131,0.649437,0.805359,1.982311,1.251119,1.491725,10.419335,27.475009,0.804905,1.968567,0.737187,0.481763,5399.513513,649.569234,127.536674,0.470998
min,1.000000,1.000000,5.184760e+05,35.400000,30.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,23.000000,3.300000,1.000000,0.100000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,1.000000,5.289040e+05,37.800000,48.000000,18.500000,1.000000,1.000000,1.000000,1.000000,2.00000,3.000000,1.000000,1.000000,1.000000,3.000000,1.000000,2.000000,38.000000,6.500000,1.000000,2.000000,1.000000,1.000000,2111.750000,0.000000,0.000000,1.000000
50%,1.000000,1.000000,5.303055e+05,38.200000,64.000000,24.500000,3.000000,2.000000,3.000000,1.000000,3.00000,3.000000,2.000000,2.000000,1.000000,5.000000,3.000000,4.000000,45.000000,7.500000,2.000000,2.250000,1.000000,1.000000,2673.500000,0.000000,0.000000,2.000000
75%,2.000000,1.000000,5.347275e+05,38.500000,88.000000,36.000000,3.000000,3.000000,4.000000,2.000000,4.00000,4.000000,3.000000,2.000000,2.000000,6.500000,4.000000,5.000000,52.000000,57.000000,3.000000,3.900000,2.000000,2.000000,3209.000000,0.000000,0.000000,2.000000
max,2.000000,9.000000,5.305629e+06,40.800000,184.000000,96.000000,4.000000,4.000000,6.000000,3.000000,5.00000,4.000000,4.000000,3.000000,3.000000,7.500000,4.000000,5.000000,75.000000,89.000000,3.000000,10.100000,3.000000,2.000000,41110.000000,7111.000000,2209.000000,2.000000

In [289]:
# horses.describe()

### Анализ столбцев  на выбросы

Выбросы обнаружены в столбцах 
- Age (должно быть 1-2)
- pulse (числа около норма 30-40 редко меньше 20, у некоторых повышенная)
- respiratory rate (норма 8-10, возможны большие колебания)
- capillary refill time (должно быть в пределах 1-2)
- total protein (нормальное значение в пределах 6-7.5)
- type of lesion (надо будет разбить на столбцы, в таком виде анализировать невозможно)

**В остальных столцах не обнаружил выбросов, есть немного завышенные значения, но мне они показались реальными**

In [290]:
# разбираемся со столбцем Age

horses['Age'].value_counts()

# Так как есть всего два варианта молодая лошадь - 1 и старая лошадь - 2
# можно предположить, что данные перепутали и 9 соттветсвует 2 (старой лошади)
# кроме того изменим тип с float на int

1.0    276
9.0     24
Name: Age, dtype: int64

In [291]:
horses['Age'] = horses['Age'].replace(9, 2).astype(int)

In [292]:
# разбираемся со столбцем Pulse

horses['pulse'].describe()

# Видно, что максимальное очень высокое, при 100 ударах уже стоит серьезная угроза жизнь
# но в то же время таких значений не очень много, а лошади больные, поэтому оставлю как есть

count    276.000000
mean      71.913043
std       28.630557
min       30.000000
25%       48.000000
50%       64.000000
75%       88.000000
max      184.000000
Name: pulse, dtype: float64

In [293]:
# разбираемся со столбцем capillary refill time

horses['capillary refill time'].value_counts()

# Есть 2 значения 3.0, возможно подрозумевалось 3 сек, этому времени соответсвует цифра 2

1.0    188
2.0     78
3.0      2
Name: capillary refill time, dtype: int64

In [294]:
horses['capillary refill time'] = horses['capillary refill time'].replace(3, 2)
horses['capillary refill time'].value_counts()

1.0    188
2.0     80
Name: capillary refill time, dtype: int64

In [295]:
# разбираемся со столбцем capillary refill time

horses['total protein'].describe()

# Достаточно много лошадей с повышенным содержание белка, поэтому также оставлю, как есть

count    267.000000
mean      24.456929
std       27.475009
min        3.300000
25%        6.500000
50%        7.500000
75%       57.000000
max       89.000000
Name: total protein, dtype: float64

In [296]:
# разбираемся со столбцами type of lesion

(horses[(horses['type of lesion 2'] > 0.0) | (horses['type of lesion 3'] > 0.0)]
 .filter(items=['type of lesion 1', 'type of lesion 2', 'type of lesion 3']) )
# В некоторых строках содрежатся только 0, из описания можно сделать вывод, что у лошади
# не было поражения тканей
# по первому квартилю и отфильтровав данные, мы видим, что type of lesion 2 втречаются у 7, а 
# type of lesion 3 у одной, поэтому эти два сотлбца можно вообще удалить

     type of lesion 1  type of lesion 2  type of lesion 3
63             2209.0            1400.0               0.0
111            3111.0            7111.0               0.0
116            3205.0            3111.0               0.0
118            3112.0            6112.0               0.0
178            6111.0            3111.0               0.0
206            6111.0            3112.0               0.0
229            4205.0            3111.0            2209.0

In [297]:
del horses['type of lesion 2']
del horses['type of lesion 3']

In [298]:
#Теперь работаем только со столбцом type of lesion 1, его разобьем на 4:
# site of lesion
# type of lesion
# subtype
# specific code
# это проще всего сделать с помощью функции 
def split_type_of_lesinon(data):
    
    data = int(data)
    if data == 0:
        first = -999
        second = -999
        third = -999
        forth = -999
    else:
        
        data = str(data)
        if int(data[0:2]) == 11 and len(data) >= 5:
            first = int(data[0:2])
            second = int(data[2])
            third = int(data[3])
            forth = int(data[4:])
        elif len(data) >= 4:
            first = int(data[0])
            second = int(data[1])
            third = int(data[2])
            forth = int(data[3:])
        else:
            try:
                first = int(data[0])
            except:
                first = np.nan
            try:
                second = int(data[1])
            except:
                first = np.nan               
            try:
                third = int(data[2])
            except:
                third = np.nan
            try:
                forth = forth = int(data[3:])
            except:
                forth = np.nan
            
    res = [first, second, third, forth]   
    return res

In [299]:
horses[['site of lesion', 'type of lesion', 'subtype', 'specific code']] = horses['type of lesion 1'].apply(split_type_of_lesinon).apply(pd.Series)

In [300]:
horses[['site of lesion', 'type of lesion', 'subtype', 'specific code']].describe()

# Тепрь видно, что в subtype ошибка, он должен принимать значения от 1 до 2
# Значение 3 всего одно, поэтому будем считать, что это человекческий фактор и
# и собирались поставить n/a
# В столбцах subtype и specific code есть 0, что из описания начит нет данных

       site of lesion  type of lesion     subtype  specific code
count      300.000000      300.000000  300.000000     294.000000
mean      -183.776667     -185.083333 -186.046667    -186.972789
std        391.205332      390.575550  390.112896     394.572295
min       -999.000000     -999.000000 -999.000000    -999.000000
25%          2.000000        1.000000    0.000000       0.000000
50%          3.000000        1.000000    0.000000       2.500000
75%          3.000000        2.000000    1.000000       5.000000
max         11.000000        4.000000    3.000000      10.000000

In [301]:
horses['subtype'] = horses['subtype'].replace(3, np.nan)
horses['subtype'] = horses['subtype'].replace(0, np.nan)
horses['specific code'] = horses['specific code'].replace(0, np.nan)

In [302]:
# Столбец type of lesion 1 больше не нужен

del horses['type of lesion 1']

### Анализ столбцев на пропуски

Переходим к работе с пропусками

In [303]:
horses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   surgery                      299 non-null    float64
 1   Age                          300 non-null    int32
 2   Hospital Number              300 non-null    float64
 3   rectal temperature           240 non-null    float64
 4   pulse                        276 non-null    float64
 5   respiratory rate             242 non-null    float64
 6   temperature of extremities   244 non-null    float64
 7   peripheral pulse             231 non-null    float64
 8   mucous membranes             253 non-null    float64
 9   capillary refill time        268 non-null    float64
 10  pain                         245 non-null    float64
 11  peristalsis                  256 non-null    float64
 12  abdominal distension         244 non-null    float64
 13  nasogastric tube             196 non-null    float64
 14  nasogastric reflux           194 non-null    float64
 15  nasogastric reflux PH        53 non-null     float64
 16  rectal examination - feces   198 non-null    float64
 17  abdomen                      182 non-null    float64
 18  packed cell volume           271 non-null    float64
 19  total protein                267 non-null    float64
 20  abdominocentesis appearance  135 non-null    float64
 21  abdomcentesis total protein  102 non-null    float64
 22  outcome                      299 non-null    float64
 23  surgical lesion              300 non-null    float64
 24  cp_data                      300 non-null    float64
 25  site of lesion               300 non-null    float64
 26  type of lesion               300 non-null    float64
 27  subtype                      158 non-null    float64
 28  specific code                265 non-null    float64
dtypes: float64(28), int32(1)
memory usage: 66.9 KB

In [304]:
# 0 Surgery и 22 Outcome заполню медианой, пропущено всего одно значение,
# поэтому это точно не исказит статистику

horses.surgery.fillna(horses.surgery.median(), inplace=True)
horses.outcome.fillna(horses.outcome.median(), inplace=True)

In [305]:
# 15 nasogastric reflux PH, пропущено 5/6 информации, скорее всего тест на кислотность
# проводили не всем, не думаю, что это важно поэтому удалю

# Аналогично с 21 abdomcentesis total protein

del horses['nasogastric reflux PH']
del horses['abdomcentesis total protein']

In [306]:
# 27 subtype
# доступна всего 1/2 значений, скорее всего врачи это просто пропускали, как не
# очень важный пункт, использовать я его не собираюсь, поэтому удалю

del horses['subtype']

In [307]:
# Заполним стобец 10 Pain на медианой, сгрупперуем по столбцам 
# site of lesion 
# type of lesion
# outcome
# Age
# в зависимости от первого места поражения, типа поражения, выживаемости и возраста,
# скорее всего можно сделать вывод о том, насколько сильная была боль

horses.pain.fillna(horses.groupby(['site of lesion', 'type of lesion', 'outcome', 'Age']).pain.transform('median'), inplace=True)

In [308]:
# 20 abdominocentesis appearance, восстонавлю в зависимости от первого места поражения, 
# типа поражения, выживаемости и возраста, скорее всего у одинаково больных
# лошадей будет одинаковый цвет кишечника

horses['abdominocentesis appearance'].fillna(horses.groupby(['site of lesion', 'type of lesion', 'outcome', 'Age'])['abdominocentesis appearance'].transform('median'), inplace=True)

In [309]:
# 13 nasogastric tube 
# большое количество газа причиняет дискомфор, восстановлю медианой 
# в зависимости от степени боли и болезни
# аналогично поступлю для 14 nasogastric reflux, он отвечает за прохдимость жидкости

horses['nasogastric tube'].fillna(horses.groupby(['pain', 'site of lesion', 'type of lesion'])['nasogastric tube'].transform('median'), inplace=True)

horses['nasogastric reflux'].fillna(horses.groupby(['pain', 'site of lesion', 'type of lesion'])['nasogastric reflux'].transform('median'), inplace=True)

In [310]:
# 17 abdomen
# информация о животе буду заполнять медианой
# зависит от хирургического вмешательства, также скорее всего зависит от болезни

horses.abdomen.fillna(horses.groupby(['surgery', 'site of lesion', 'type of lesion']).abdomen.transform('median'), inplace=True)

In [311]:
# 16 rectal examination - feces
# сотояние кала, скорее всего напрямую зависит от болезни

horses['rectal examination - feces'].fillna(horses.groupby(['site of lesion', 'type of lesion'])['rectal examination - feces'].transform('median'), inplace=True)

In [312]:
# 4 pulse и 3 rectal temperature
# Пульс и температура повышается при шоковом состоянии лошади
# Заполню медианой в зависимости от столбца pain

horses.pulse.fillna(horses.groupby(['pain']).pulse.transform('median'), inplace=True)
horses['rectal temperature'].fillna(horses.groupby(['pain'])['rectal temperature'].transform('median'), inplace=True)

In [313]:
# 5 respiratory rate
# полезность сомнительна из-за больших колебаний, поэтому удаляем

del horses['respiratory rate']

In [314]:
# 6 temperature of extremities
# Связана с ректальной температурой и шоковым состоянием лошади

horses['temperature of extremities'].fillna(horses.groupby(['pain', 'rectal temperature'])['temperature of extremities'].transform('median'), inplace=True)

In [315]:
# 7 peripheral pulse
# Переферческий пульс, логчно предположить, что зависит от обчного пульса

horses['peripheral pulse'].fillna(horses.groupby(['pulse'])['peripheral pulse'].transform('median'), inplace=True)

In [316]:
# 8 mucous membranes
# Цвет слизистых оболочк, скорее всего зависит от заболевания

horses['mucous membranes'].fillna(horses.groupby(['site of lesion'])['mucous membranes'].transform('median'), inplace=True)

In [317]:
# 9 capillary refill time
# Зависит от пульса

horses['capillary refill time'].fillna(horses.groupby(['pulse'])['capillary refill time'].transform('median'), inplace=True)

In [318]:
# 11 peristalsis
# Зависит от активности лошади, скорее всего на активность лошади влияет уровнь боль
# если лошадь испытывает сильную боль она не будет активной

horses['peristalsis'].fillna(horses.groupby(['pain'])['peristalsis'].transform('median'), inplace=True)

In [319]:
# 12 abdominal distension
# Зависит от уровня боли, а также часто связано с хирургическим вмешательством

horses['abdominal distension'].fillna(horses.groupby(['surgery', 'pain'])['abdominal distension'].transform('median'), inplace=True)

In [320]:
# 18 packed cell volume
# Изменяется в зависимости от кровообращения, поэтому буду считать что связано
# с пульсом

horses['packed cell volume'].fillna(horses.groupby(['pulse'])['packed cell volume'].transform('median'), inplace=True)

In [321]:
# 19 total protein
# Значения зависят от уровня обезвоживания, предыдущий параметр также отражал 
# степень обезвоживания, поэтому свяжу с ним

horses['total protein'].fillna(horses.groupby(['packed cell volume'])['total protein'].transform('median'), inplace=True)

In [322]:
# 28 specific code

# Определяет характеристику поражения, скорее всего связан с местом поражения,
# типом, и может быть со степенью боли, логично предположить, что при разном
# при разных характеристиках поражения, животное чувстовало себя по-разному

horses['specific code'].fillna(horses.groupby(['site of lesion', 'type of lesion', 'pain'])['specific code'].transform('median'), inplace=True)

In [323]:
horses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   surgery                      300 non-null    float64
 1   Age                          300 non-null    int32
 2   Hospital Number              300 non-null    float64
 3   rectal temperature           297 non-null    float64
 4   pulse                        298 non-null    float64
 5   temperature of extremities   279 non-null    float64
 6   peripheral pulse             290 non-null    float64
 7   mucous membranes             300 non-null    float64
 8   capillary refill time        294 non-null    float64
 9   pain                         293 non-null    float64
 10  peristalsis                  296 non-null    float64
 11  abdominal distension         293 non-null    float64
 12  nasogastric tube             274 non-null    float64
 13  nasogastric reflux           281 non-null    float64
 14  rectal examination - feces   292 non-null    float64
 15  abdomen                      288 non-null    float64
 16  packed cell volume           298 non-null    float64
 17  total protein                294 non-null    float64
 18  abdominocentesis appearance  275 non-null    float64
 19  outcome                      300 non-null    float64
 20  surgical lesion              300 non-null    float64
 21  cp_data                      300 non-null    float64
 22  site of lesion               300 non-null    float64
 23  type of lesion               300 non-null    float64
 24  specific code                265 non-null    float64
dtypes: float64(24), int32(1)
memory usage: 57.5 KB

### Промежуточный итог
Многие столбцы почти полностью заполнены(где пропусков от 1 до 12), поэтому пропуски заполню медианами этих столбцов, логчно предположить, что несколько отдельных особей будут обладать параметрами большинства, в любом случае это не сильно исказит данные

Так же на этом этапе переведу некоторые столбцы в int

In [324]:
horses['rectal temperature'].fillna(horses['rectal temperature'].median(), inplace=True)

horses['Hospital Number'] = horses['Hospital Number'].astype(int)

horses['pulse'].fillna(horses['pulse'].median(), inplace=True)
horses['pulse'] = horses['pulse'].astype(int)

horses['peripheral pulse'].fillna(horses['peripheral pulse'].median(), inplace=True)
horses['peripheral pulse'] = horses['peripheral pulse'].astype(int)

horses['mucous membranes'] = horses['mucous membranes'].astype(int)

horses['capillary refill time'].fillna(horses['capillary refill time'].median(), inplace=True)
horses['capillary refill time'] = horses['capillary refill time'].astype(int)

horses['pain'].fillna(horses['pain'].median(), inplace=True)
horses['pain'] = horses['pain'].astype(int)

horses['peristalsis'].fillna(horses['peristalsis'].median(), inplace=True)
horses['peristalsis'] = horses['peristalsis'].astype(int)

horses['abdominal distension'].fillna(horses['abdominal distension'].median(), inplace=True)
horses['abdominal distension'] = horses['abdominal distension'].astype(int)

horses['rectal examination - feces'].fillna(horses['rectal examination - feces'].median(), inplace=True)
horses['rectal examination - feces'] = horses['rectal examination - feces'].astype(int)

horses['peristalsis'].fillna(horses['peristalsis'].median(), inplace=True)
horses['peristalsis'] = horses['peristalsis'].astype(int)

horses['abdomen'].fillna(horses['abdomen'].median(), inplace=True)
horses['abdomen'] = horses['abdomen'].astype(int)

horses['packed cell volume'].fillna(horses['packed cell volume'].median(), inplace=True)
horses['packed cell volume'] = horses['packed cell volume'].astype(int)

horses['total protein'].fillna(horses['total protein'].median(), inplace=True)

horses = horses.astype({'outcome' : int, 
                        'surgical lesion' : int, 
                        'cp_data' : int, 
                        'site of lesion' : int, 
                        'type of lesion' : int, 
                        'surgery' : int})

In [325]:
horses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   surgery                      300 non-null    int32
 1   Age                          300 non-null    int32
 2   Hospital Number              300 non-null    int32
 3   rectal temperature           300 non-null    float64
 4   pulse                        300 non-null    int32
 5   temperature of extremities   279 non-null    float64
 6   peripheral pulse             300 non-null    int32
 7   mucous membranes             300 non-null    int32
 8   capillary refill time        300 non-null    int32
 9   pain                         300 non-null    int32
 10  peristalsis                  300 non-null    int32
 11  abdominal distension         300 non-null    int32
 12  nasogastric tube             274 non-null    float64
 13  nasogastric reflux           281 non-null    float64
 14  rectal examination - feces   300 non-null    int32
 15  abdomen                      300 non-null    int32
 16  packed cell volume           300 non-null    int32
 17  total protein                300 non-null    float64
 18  abdominocentesis appearance  275 non-null    float64
 19  outcome                      300 non-null    int32
 20  surgical lesion              300 non-null    int32
 21  cp_data                      300 non-null    int32
 22  site of lesion               300 non-null    int32
 23  type of lesion               300 non-null    int32
 24  specific code                265 non-null    float64
dtypes: float64(7), int32(18)
memory usage: 37.6 KB

Осталось 5 столбца с пропусками разберем каждый отдельно

In [326]:
# 7 temperature of extremities
# Температура конечностей
# Дозаполню ее в зависимотси от болезни и уровня боли

horses['temperature of extremities'].fillna(horses.groupby(['site of lesion', 'pain'])['temperature of extremities'].transform('median'), inplace=True)
# Остается 3 значения, их вставлю как у большинства
horses['temperature of extremities'].fillna(horses['temperature of extremities'].median(), inplace=True)

# 14 nasogastric tube
# Исследования нозагостральным зондом, от заначений зависит комфорт лошади
# Дозаполню в зависимости от уровня боли
horses['nasogastric tube'].fillna(horses.groupby(['pain'])['nasogastric tube'].transform('median'), inplace=True)

# 15 nasogastric reflux
# Определяет проходимость жидкости, скорее всего непроходимость будет вызывать 
# боли, поэтому свяжу с уровнем боли
horses['nasogastric reflux'].fillna(horses.groupby(['pain'])['nasogastric reflux'].transform('median'), inplace=True)

# 21 abdominocentesis appearance
# Внешний вид брюшной полости
# Скорее всего связан с местом поражения и уровнем боли
horses['abdominocentesis appearance'].fillna(horses.groupby(['site of lesion', 'pain'])['abdominocentesis appearance'].transform('median'), inplace=True)
# Остается 6 значений, их вставлю как у большинства
horses['abdominocentesis appearance'].fillna(horses['abdominocentesis appearance'].median(), inplace=True)

# 28 specific code
# Более точно характеризует поражение
# Скорее всего связан с местом поражения и уровнем боли
horses['specific code'].fillna(horses.groupby(['site of lesion', 'pain'])['specific code'].transform('median'), inplace=True)
# Остается 17 значений, дозаполню только по месту поражения
horses['specific code'].fillna(horses.groupby(['site of lesion'])['specific code'].transform('median'), inplace=True)
# Остается 6 значений, их вставлю как у большинства
horses['specific code'].fillna(horses['specific code'].median(), inplace=True)


horses = horses.astype({'temperature of extremities' : int, 
                        'nasogastric tube' : int, 
                        'nasogastric reflux' : int, 
                        'abdominocentesis appearance' : int, 
                        'specific code' : int})

In [327]:
horses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   surgery                      300 non-null    int32
 1   Age                          300 non-null    int32
 2   Hospital Number              300 non-null    int32
 3   rectal temperature           300 non-null    float64
 4   pulse                        300 non-null    int32
 5   temperature of extremities   300 non-null    int32
 6   peripheral pulse             300 non-null    int32
 7   mucous membranes             300 non-null    int32
 8   capillary refill time        300 non-null    int32
 9   pain                         300 non-null    int32
 10  peristalsis                  300 non-null    int32
 11  abdominal distension         300 non-null    int32
 12  nasogastric tube             300 non-null    int32
 13  nasogastric reflux           300 non-null    int32
 14  rectal examination - feces   300 non-null    int32
 15  abdomen                      300 non-null    int32
 16  packed cell volume           300 non-null    int32
 17  total protein                300 non-null    float64
 18  abdominocentesis appearance  300 non-null    int32
 19  outcome                      300 non-null    int32
 20  surgical lesion              300 non-null    int32
 21  cp_data                      300 non-null    int32
 22  site of lesion               300 non-null    int32
 23  type of lesion               300 non-null    int32
 24  specific code                300 non-null    int32
dtypes: float64(2), int32(23)
memory usage: 31.8 KB

DataFrame полностью заполнен

In [328]:
horses.head()

,surgery,Age,Hospital Number,rectal temperature,pulse,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,pain,peristalsis,abdominal distension,nasogastric tube,nasogastric reflux,rectal examination - feces,abdomen,packed cell volume,total protein,abdominocentesis appearance,outcome,surgical lesion,cp_data,site of lesion,type of lesion,specific code
0,2,1,530101,38.5,66,3,3,1,2,5,4,4,2,1,3,5,45,8.4,2,2,2,2,11,3,4
1,1,1,534817,39.2,88,2,3,4,1,3,4,2,2,1,4,2,50,85.0,2,3,2,2,2,2,8
2,2,1,530334,38.3,40,1,1,3,1,3,3,1,1,1,1,1,33,6.7,1,1,2,1,-999,-999,-999
3,1,2,5290409,39.1,164,4,1,6,2,2,4,4,1,2,3,4,48,7.2,3,2,1,1,2,2,8
4,2,1,530255,37.3,104,3,3,6,2,4,3,3,1,2,2,3,74,7.4,2,2,2,2,4,3,5